version: 2.1
language: node_js
node_js:
  - '12'
cache:
  yarn: true
  directories:
    - public
    - .cache
script:
  - npm run build # Generate static HTML files

# Here is the magic part
deploy:
  # Use Github pages deploy process
  provider: pages

  # Git branch on which it should deploy (master, gh-pages, foo...)
  target_branch: gh-pages
